server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:rpgmanager.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.rpgmanager: DEBUG
